In [1]:
f = open("c:/테스트폴더/새파일.txt","a") # append=a -> 기존의 내용을 살린상태에서 추가하고 싶을 때
f.write("ㅋㅋㅋ")
f.close()

In [2]:
with open("c:/테스트폴더/새파일.txt","a") as f:
    f.write(" ㅎㅎㅎ")

In [3]:
class FourCal:
    #self.first : class의 정적인 속성들이다
    #self.second
    # class안에 위치해 있지만 구성속성으로 인식되진 못하므로 self를 넣어줘야 함
    def setdata(self, a, b):
        self.first = a
        self.second = b
    def add(self): # self는 class에 포함된 동작이다. class는 식구같은 느낌
        result = self.first + self.second #self가 붙으면 이 class에 대한 구성요소가 됨 / result는 class의 속성이라고는 할 수 없음
        return result
    def mul(self):
        result = self.first * self.second #self가 붙으면 이 class에 대한 구성요소가 됨 
        return result
aCal = FourCal() # 소나타를 가지고 차 두대를 만들기로 했을때 
bCal = FourCal()
aCal.setdata(4,2) #a에는 빨강선팅을 셋팅
print(aCal.add())
bCal.setdata(3,8) #b에는 검정선팅을 셋팅(설계도는 같지만 옵션이 다름)
print(bCal.add())

6
11


In [4]:
class FourCal:
    #self.first : class의 정적인 속성들이다
    #self.second
    # class안에 위치해 있지만 구성속성으로 인식되진 못하므로 self를 넣어줘야 함
    def __init__(self, a, b):
        self.first = a
        self.second = b
    def add(self): # self는 class에 포함된 동작이다. class는 식구같은 느낌
        result = self.first + self.second #self가 붙으면 이 class에 대한 구성요소가 됨 / result는 class의 속성이라고는 할 수 없음
        return result
    def mul(self):
        result = self.first * self.second #self가 붙으면 이 class에 대한 구성요소가 됨 
        return result
aCal = FourCal(4,2) # 아예 만들때부터 셋팅에서 출고하는 과정
bCal = FourCal(3,8)
print(aCal.add())
print(bCal.add())

6
11


In [5]:
class FourCal:
    def __init__(self, a, b):
        self.first = a
        self.second = b
    def add(self): 
        result = self.first + self.second 
        return result
    def mul(self):
        result = self.first * self.second 
        return result
    def div(self):
        result = self.first / self.second 
        return result
class MoreFourCal(FourCal): #부모를 입력받아서 계승함(상속받음) / MoreFourCal은 사칙연산에 대한 고민 X (+기능인 pow까지 가능)
    def pow(self):
        result = self.first**self.second
        return result
    def div(self): # 기존에 있던 것을 덮어씀
        if self.second == 0:
            self.second = 0.00000000000000001
        result = self.first / self.second 
        return result
    
c = MoreFourCal(4,0)
d = c.div()
print(d)

4e+17


In [6]:
class MyMath:
    MyPI = 3.14
    
mm1 = MyMath()
mm1.MyPI = 4
mm2 = MyMath()
print(mm1.MyPI,mm2.MyPI)

4 3.14


In [7]:
import mod1 #별 말이 없으면 잘 가지고 온 것임
print(mod1.add_mod1(3,4))
print(mod1.sub_mod1(3,4))

7
-1


In [8]:
from mod1 import * #add_mod1, sub_mod1 : 필요한 함수만 import해서 충돌될 가능성 낮춤
print(add_mod1(3,4))
print(sub_mod1(3,4))

7
-1


In [9]:
import mod1 as m1
print(add_mod1(3,4))
print(sub_mod1(3,4))

7
-1


In [10]:
import mod2
print(mod2.add_mod2(3,4)) # 함수가 들어있든, class가 들어있든 맞게 입력해주면 된다.
print(mod2.PI)
mm2 = mod2.Math_mod2() #class생성
print(mm2.solve(2)) #라이브러리 불러오는 과정

7
3.14
12.56


In [11]:
import numpy as np #대수
import pandas as pd #표
import matplotlib.pyplot as plt#그래프

In [12]:
# 4/0

ZeroDivisionError: division by zero

In [ ]:
try:
    4/0
except ZeroDivisionError  as e:
    print(e)

In [ ]:
try:
    print(4/0)
except ZeroDivisionError  as e:
    print(4/0.0000000000000000001)
    #print(e)
#finally는 수행 했을 때 오류가 생기든 안생기든 수행하여야 한다

In [ ]:
def positive (l):
    result =[]
    for i in l:
        if i > 0: result.append(i)
        return result
        
print(positive([1, -3, 2, 0, -5, 6]))

In [ ]:
def positive(x):
    return x >0 
data = [1, -3, 2, 0, -5, 6]
f= filter(positive,data)
print(list(f))

In [ ]:
data = [1, -3, 2, 0, -5, 6]
list(filter(lambda x: x>0,data))

In [ ]:
a,b = input("숫자 두개를 입력하세요").split()
a = int(a)
b = int(b)
print(a+1,"그리고",b)

In [ ]:
a,b,c,d,e = map(int, input("숫자 두개를 입력하세요").split())
print(a+1,b+1,c+1,d+1,e+1)

In [15]:
data1 = [1,2,3]
data2 = [4,5,6]
data3 = [7,8,9]
list(zip(data1,data2,data3))

[(1, 4, 7), (2, 5, 8), (3, 6, 9)]

In [17]:
import os
os.environ["path"]

'C:\\ProgramData\\Anaconda3;C:\\ProgramData\\Anaconda3\\Library\\mingw-w64\\bin;C:\\ProgramData\\Anaconda3\\Library\\usr\\bin;C:\\ProgramData\\Anaconda3\\Library\\bin;C:\\ProgramData\\Anaconda3\\Scripts;C:\\Program Files\\Common Files\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\NVIDIA Corporation\\NVIDIA NvDLISR;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Java\\jdk-16.0.1\\bin;;C:\\WINDOWS\\system32;C:\

In [18]:
os.getcwd()

'C:\\Users\\CPB06GameN'

In [19]:
import glob
glob.glob('C:\\Users\\CPB06GameN\\*.py')

['C:\\Users\\CPB06GameN\\mod1.py', 'C:\\Users\\CPB06GameN\\mod2.py']

In [ ]:
# 4시~5시

In [20]:
data = [6, 7.5,8,0,1] # 출력값이 정수부분에도 점이 붙어서 나옴
arr = np.array(data)
arr

array([6. , 7.5, 8. , 0. , 1. ])

In [23]:
data2d = [[1,2,3,4],[5,6,7,8]]
data2d

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [26]:
arr2d = np.array(data2d)

In [28]:
arr2d.ndim # 2차원

2

In [30]:
arr2d.shape # 2행4열

(2, 4)

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
np.zeros((3,6)) # zeros입장에서는 튜플로 묶어줘야 함

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
np.zeros((2,3,2)) # .으로 나타낸 것: 부동소수점

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [39]:
np.zeros((2,3,2)).dtype

dtype('float64')

In [44]:
arr = np.zeros((2,3,2),dtype=np.int32)
arr.dtype

dtype('int32')

In [46]:
arr1 = np.zeros((2,3)) # 2행3열을 1로 채워 
arr2 = np.ones_like(arr1) # like : 비어있는 초기화의 행렬을 만들기위해 arr1과 차원이 같은 아이를 만듦
arr2.shape

(2, 3)

In [49]:
arr3 = np.full((2,3),5)
arr3

array([[5, 5, 5],
       [5, 5, 5]])

In [48]:
arr4 = np.eye(2)
arr4

array([[1., 0.],
       [0., 1.]])