In [1]:
import torch
import torch.nn.functional as F

In [2]:
z = torch.FloatTensor([1,2,3])

In [3]:
hypothesis = F.softmax(z,dim=0) # softmax는 1이 0.09가되고 2가 0.24가 되었다는 것은 비례한 것과 같다고 할 수 있음
hypothesis

tensor([0.0900, 0.2447, 0.6652])

In [4]:
import numpy as np
np.exp(1.0)/(np.exp(1.0)+np.exp(2.0)+np.exp(3.0))

0.09003057317038046

In [5]:
np.exp(2.0)/(np.exp(1.0)+np.exp(2.0)+np.exp(3.0))

0.24472847105479767

In [6]:
np.exp(3.0)/(np.exp(1.0)+np.exp(2.0)+np.exp(3.0))

0.6652409557748219

In [7]:
hypothesis.sum() #세 개 숫자를 다 더하면 1이 나옴(0.09+0.24+0.66) 

tensor(1.)

In [8]:
# MNIST (손글씨 인식 - 필기체)

In [9]:
!pip install torchvision

In [6]:
import torch
import torch.nn as nn
import torchvision.datasets as dsets
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import random
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# cuda가 지원되는 상황이라면 그것을 쓰고 아니면 CPU를 쓰자 / cuda process가 gpu에 들어있음

In [7]:
mnist_train = dsets.MNIST(root ='MNIST_data/',
                         train = True,
                         transform = transforms.ToTensor(),
                         download=True)
mnist_test = dsets.MNIST(root ='MNIST_data/',
                         train = False,
                         transform = transforms.ToTensor(),
                         download=True)
train_epochs = 15
batch_size = 100

data_loader = torch.utils.data.DataLoader(dataset=mnist_train,batch_size = batch_size,shuffle=True,drop_last=True)

C:\ProgramData\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:498: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:180.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [8]:
mnist_train[0]

(tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000],
          [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
           0.0000, 0.0000, 0.0000, 0.0000, 

In [9]:
image,label = mnist_train[0]
print(image.shape,label) # torch.Size([1, 28, 28]) 5 : 가로가 28개, 세로가 28개, 앞의 1은 흑백을 의미

torch.Size([1, 28, 28]) 5


In [ ]:
import matplotlib.pyplot as plt
plt.imshow(image.reshape(28,28),cmap='gray')

#img = np.reshape(image,[28,28])
#plt.imshow(img, xmap='Greys')

In [10]:
linear = nn.Linear( 28*28, 10, bias = True) #가로세로가 28*28픽셀, 10개로 출력

In [11]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.1)

In [20]:
for epoch in range (train_epochs):
    avg_cost=0
    total_batch = len(data_loader)
    
    for X,y in data_loader:
        X = X.view(-1,28*28)
        y = y
        
        hypothesis = linear(X)
        cost = criterion(hypothesis, y)
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
        
        avg_cost += cost/total_batch #하나씩 증가할 때마다 나눠서 보여줌

    print('Epoch:','%04d' %(epoch+1), 'cost=', "{:.9f}".format(avg_cost)) 
print("Finished")        

Epoch: 0001 cost= 0.300403595
Epoch: 0002 cost= 0.295198411
Epoch: 0003 cost= 0.290986270
Epoch: 0004 cost= 0.287272334
Epoch: 0005 cost= 0.284530520
Epoch: 0006 cost= 0.281947613
Epoch: 0007 cost= 0.279566228
Epoch: 0008 cost= 0.277865499
Epoch: 0009 cost= 0.276108772
Epoch: 0010 cost= 0.274576604
Epoch: 0011 cost= 0.272825330
Epoch: 0012 cost= 0.271739066
Epoch: 0013 cost= 0.270471007
Epoch: 0014 cost= 0.269451052
Epoch: 0015 cost= 0.268361479
Finished


In [21]:
with torch.no_grad():
    X_test = mnist_test.test_data.view(-1,28*28).float()
    y_test = mnist_test.test_labels
    
    prediction = linear(X_test)
    
    correct_prediction = torch.argmax(prediction,1) == y_test
    accuracy = correct_prediction.float().mean()
    print("add:", accuracy.item())
    r = random.randint(0,len(mnist_test)-1)
    X_single_data = mnist_test.test_data[r:r+1].view(-1,28*28).float()
    y_single_Data = mnist_test.test_labels[r:r+1]
    print('Label:',y_single_Data.item())
    single_prediction = linear(X_single_data)
    print('Prediction:', torch.argmax(single_prediction,1).item())
    
    #plt.imshow(mnist_test.test_data[r:r+1].view(28,28),cmap = 'Greys',interpolation='nearest')
    #plt.show()

add: 0.8833000063896179
Label: 8
Prediction: 8


C:\ProgramData\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:67: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
C:\ProgramData\Anaconda3\lib\site-packages\torchvision\datasets\mnist.py:57: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [ ]:
# Neural Network - Deep learning

In [24]:
# layering
# nn.Linear(784,10)
linear1 = nn.Linear(784,256,bias=True)
linear2 = nn.Linear(256,256,bias=True)
linear3 = nn.Linear(256,10,bias=True)
relu = torch.nn.ReLU()

In [26]:
nn.init.normal_(linear1.weight)
nn.init.normal_(linear2.weight)
nn.init.normal_(linear3.weight)

Parameter containing:
tensor([[-0.4590,  0.5212,  1.2280,  ...,  0.9788,  1.0443,  1.5466],
        [-1.2946, -0.8021, -0.2609,  ...,  0.7014, -0.0790,  0.1747],
        [-0.8793, -1.5292, -1.0541,  ..., -0.4488,  0.3271, -0.6927],
        ...,
        [ 0.5058,  0.4054, -1.3323,  ...,  0.1273, -0.3660,  2.3097],
        [ 0.0771,  1.4641,  1.2690,  ...,  0.1345,  1.0522,  0.8816],
        [ 1.0023, -0.9512, -0.0636,  ...,  0.5942,  0.5416,  0.5812]],
       requires_grad=True)

In [27]:
model = nn.Sequential(linear1, relu, linear2, relu, linear3)

In [29]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.001)
total_batch = len(data_loader)
train_epochs = 15
batch_size = 100
for epoch in range(train_epochs):
    avg_cost = 0
    for X, y in data_loader:
        X=X.view(-1,28*28)
        y=y
        optimizer.zero_grad()
        hyp = model(X)
        cost = criterion(hyp,y)
        cost.backward()
        optimizer.step()
        avg_cost+=cost/total_batch
    print('Epoch:',"%04d"%(epoch+1),'cost=','{:0.9f}'.format(avg_cost))
print("End")

Epoch: 0001 cost= 134.980957031
Epoch: 0002 cost= 36.327091217
Epoch: 0003 cost= 22.524799347
Epoch: 0004 cost= 15.584207535
Epoch: 0005 cost= 11.134097099
Epoch: 0006 cost= 8.086806297
Epoch: 0007 cost= 6.105391502
Epoch: 0008 cost= 4.434814930
Epoch: 0009 cost= 3.223149538
Epoch: 0010 cost= 2.411319256
Epoch: 0011 cost= 1.879003167
Epoch: 0012 cost= 1.278884888
Epoch: 0013 cost= 0.990485668
Epoch: 0014 cost= 0.727464080
Epoch: 0015 cost= 0.707701802
End


In [30]:
with torch.no_grad():
    X_test = mnist_test.test_data.view(-1,28*28).float()
    y_test = mnist_test.test_labels
    
    prediction = linear(X_test)
    
    correct_prediction = torch.argmax(prediction,1) == y_test
    accuracy = correct_prediction.float().mean()
    print("add:", accuracy.item())
    r = random.randint(0,len(mnist_test)-1)
    X_single_data = mnist_test.test_data[r:r+1].view(-1,28*28).float()
    y_single_Data = mnist_test.test_labels[r:r+1]
    print('Label:',y_single_Data.item())
    single_prediction = linear(X_single_data)
    print('Prediction:', torch.argmax(single_prediction,1).item())
    
    #plt.imshow(mnist_test.test_data[r:r+1].view(28,28),cmap = 'Greys',interpolation='nearest')
    #plt.show()

add: 0.8833000063896179
Label: 0
Prediction: 0
